//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App_Hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patients
    {
        public int Patient_ID { get; set; }
        public string Patient_Fanme { get; set; }
        public string Patient_Lname { get; set; }
        public string Patient_Address { get; set; }
        public System.DateTime Patient_Date { get; set; }
        public Nullable<System.DateTime> Patient_InsertionDateTime { get; set; }
    }
}
